### ISSUE TITLE
GO binding struct for a self referencing struct

### ISSUE THREAD

**Issue by vposham** [draffensperger/go-interlang#4]
Hi,

Any ideas on how to write a golang equivalent struct for self referencing struct something like this - 

typedef struct WRITER {
int version;
int (*WriteBlock)(struct WRITER* thisPtr,
const void* dataBufferPtr,
unsigned long bufferSize);
} WRITER;

Thanks.

**Comment by draffensperger** [comment]
Given that [cgo](https://golang.org/cmd/cgo/) allows you to reference C types via something like `C.WRITER`, in this case would it make sense to just reference the C types directly? Then maybe you could have a Go wrapper for a higher level concept in your program such as the thing that does the writing using the underlying struct.

**Comment by vposham** [comment]
Disclaimer : Im a C noob who just came to know that - there is something like self referencing structs.

I tried directly referencing C struct like C.WRITER, but the WriteBlock method implementation is required to use the object in a meaningful way.

To give more context - Im trying to write a Go struct wrapper for [FPDF_FILEWRITE_](https://pdfium.googlesource.com/pdfium/+/refs/heads/master/public/fpdf_save.h) struct to use in [FPDF_SaveAsCopy](https://pdfium.googlesource.com/pdfium/+/refs/heads/master/public/fpdf_save.h) function.

https://pdfium.googlesource.com/pdfium/+/refs/heads/master/public/fpdf_save.h

**Comment by vposham** [comment]
Digging further, I came to know that something like [this](https://github.com/vmiklos/vmexam/blob/40301f095892b804248f5f4936afce185a11eb74/pdfium/test.cxx#L110) needs to be implemented in GO.
